[server]
#port=5004
runOnSave=true
maxUploadSize=30
enableStaticServing = false
headless = true

[client]
toolbarMode = "auto"
showSidebarNavigation=false


[theme]
font = "sans serif"
primaryColor="#FFFF"
base="dark"